module.exports={
    userType:{
        customer:"CUSTOMER",
        engineer:"ENGINEER",
        admin:"ADMIN"
    },
    userStatus:{
        pending:"PENDING",
        approved:"APPROVED",
        rejected:"REJECTED"
    },
    ticketStatus:{
        open:"OPEN",
        blocked:"BLOCKED",
        closed:"CLOSED"
    }
}